import type { Metadata } from "next";
import "./globals.css";
import Header from "./_layout/header";
import Footer from "./_layout/footer";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="font-inter">
                <Header />
                <div className="min-h-screen">{children}</div>
                <Footer />
            </body>
        </html>
    );
}
